#cloud-config
write_files:
  - path: /opt/bin/curl-retry.sh
    permissions: '0755'
    owner: root
    content: |
      #!/bin/sh -x
      until curl $@
      do sleep 1
      done
  - permissions: '0600'
    owner: root
    content: >
      WEAVE_PASSWORD="aa28e88e522463246cc79cdae6705cdd92e41f75d2db781104f23209293d5757"

      WEAVE_PEERS=""

      BREAKOUT_ROUTE="10.2.0.0/16"

      BRIDGE_ADDRESS_CIDR="10.2.0.1/24"
    path: /etc/weave.kube-00.env
  - permissions: '0600'
    owner: root
    content: >
      WEAVE_PASSWORD="aa28e88e522463246cc79cdae6705cdd92e41f75d2db781104f23209293d5757"

      WEAVE_PEERS="kube-00"

      BREAKOUT_ROUTE="10.2.0.0/16"

      BRIDGE_ADDRESS_CIDR="10.2.1.1/24"
    path: /etc/weave.kube-01.env
  - permissions: '0600'
    owner: root
    content: >
      WEAVE_PASSWORD="aa28e88e522463246cc79cdae6705cdd92e41f75d2db781104f23209293d5757"

      WEAVE_PEERS="kube-00"

      BREAKOUT_ROUTE="10.2.0.0/16"

      BRIDGE_ADDRESS_CIDR="10.2.2.1/24"
    path: /etc/weave.kube-02.env
  - path: /etc/kubernetes/addons/skydns-rc.yaml
    owner: root
    permissions: '0640'
    encoding: base64
    content: YXBpVmVyc2lvbjogdjEKa2luZDogUmVwbGljYXRpb25Db250cm9sbGVyCm1ldGFkYXRhOgogIG5hbWU6IGt1YmUtZG5zLXY5CiAgbmFtZXNwYWNlOiBrdWJlLXN5c3RlbQogIGxhYmVsczoKICAgIGs4cy1hcHA6IGt1YmUtZG5zCiAgICB2ZXJzaW9uOiB2OQogICAga3ViZXJuZXRlcy5pby9jbHVzdGVyLXNlcnZpY2U6ICJ0cnVlIgpzcGVjOgogIHJlcGxpY2FzOiAzCiAgc2VsZWN0b3I6CiAgICBrOHMtYXBwOiBrdWJlLWRucwogICAgdmVyc2lvbjogdjkKICB0ZW1wbGF0ZToKICAgIG1ldGFkYXRhOgogICAgICBsYWJlbHM6CiAgICAgICAgazhzLWFwcDoga3ViZS1kbnMKICAgICAgICB2ZXJzaW9uOiB2OQogICAgICAgIGt1YmVybmV0ZXMuaW8vY2x1c3Rlci1zZXJ2aWNlOiAidHJ1ZSIKICAgIHNwZWM6CiAgICAgIGNvbnRhaW5lcnM6CiAgICAgIC0gbmFtZTogZXRjZAogICAgICAgIGltYWdlOiBnY3IuaW8vZ29vZ2xlX2NvbnRhaW5lcnMvZXRjZDoyLjAuOQogICAgICAgIHJlc291cmNlczoKICAgICAgICAgIGxpbWl0czoKICAgICAgICAgICAgY3B1OiAxMDBtCiAgICAgICAgICAgIG1lbW9yeTogNTBNaQogICAgICAgIGNvbW1hbmQ6CiAgICAgICAgLSAvdXNyL2xvY2FsL2Jpbi9ldGNkCiAgICAgICAgLSAtZGF0YS1kaXIKICAgICAgICAtIC92YXIvZXRjZC9kYXRhCiAgICAgICAgLSAtbGlzdGVuLWNsaWVudC11cmxzCiAgICAgICAgLSBodHRwOi8vMTI3LjAuMC4xOjIzNzksaHR0cDovLzEyNy4wLjAuMTo0MDAxCiAgICAgICAgLSAtYWR2ZXJ0aXNlLWNsaWVudC11cmxzCiAgICAgICAgLSBodHRwOi8vMTI3LjAuMC4xOjIzNzksaHR0cDovLzEyNy4wLjAuMTo0MDAxCiAgICAgICAgLSAtaW5pdGlhbC1jbHVzdGVyLXRva2VuCiAgICAgICAgLSBza3lkbnMtZXRjZAogICAgICAgIHZvbHVtZU1vdW50czoKICAgICAgICAtIG5hbWU6IGV0Y2Qtc3RvcmFnZQogICAgICAgICAgbW91bnRQYXRoOiAvdmFyL2V0Y2QvZGF0YQogICAgICAtIG5hbWU6IGt1YmUyc2t5CiAgICAgICAgaW1hZ2U6IGdjci5pby9nb29nbGVfY29udGFpbmVycy9rdWJlMnNreToxLjExCiAgICAgICAgcmVzb3VyY2VzOgogICAgICAgICAgbGltaXRzOgogICAgICAgICAgICBjcHU6IDEwMG0KICAgICAgICAgICAgbWVtb3J5OiA1ME1pCiAgICAgICAgYXJnczoKICAgICAgICAjIGNvbW1hbmQgPSAiL2t1YmUyc2t5IgogICAgICAgIC0gLWRvbWFpbj1rdWJlLmxvY2FsCiAgICAgICAgLSAta3ViZV9tYXN0ZXJfdXJsPWh0dHA6Ly9rdWJlLTAwOjgwODAKICAgICAgLSBuYW1lOiBza3lkbnMKICAgICAgICBpbWFnZTogZ2NyLmlvL2dvb2dsZV9jb250YWluZXJzL3NreWRuczoyMDE1LTAzLTExLTAwMQogICAgICAgIHJlc291cmNlczoKICAgICAgICAgIGxpbWl0czoKICAgICAgICAgICAgY3B1OiAxMDBtCiAgICAgICAgICAgIG1lbW9yeTogNTBNaQogICAgICAgIGFyZ3M6CiAgICAgICAgIyBjb21tYW5kID0gIi9za3lkbnMiCiAgICAgICAgLSAtbWFjaGluZXM9aHR0cDovL2xvY2FsaG9zdDo0MDAxCiAgICAgICAgLSAtYWRkcj0wLjAuMC4wOjUzCiAgICAgICAgLSAtZG9tYWluPWt1YmUubG9jYWwKICAgICAgICBwb3J0czoKICAgICAgICAtIGNvbnRhaW5lclBvcnQ6IDUzCiAgICAgICAgICBuYW1lOiBkbnMKICAgICAgICAgIHByb3RvY29sOiBVRFAKICAgICAgICAtIGNvbnRhaW5lclBvcnQ6IDUzCiAgICAgICAgICBuYW1lOiBkbnMtdGNwCiAgICAgICAgICBwcm90b2NvbDogVENQCiAgICAgICAgbGl2ZW5lc3NQcm9iZToKICAgICAgICAgIGh0dHBHZXQ6CiAgICAgICAgICAgIHBhdGg6IC9oZWFsdGh6CiAgICAgICAgICAgIHBvcnQ6IDgwODAKICAgICAgICAgICAgc2NoZW1lOiBIVFRQCiAgICAgICAgICBpbml0aWFsRGVsYXlTZWNvbmRzOiAzMAogICAgICAgICAgdGltZW91dFNlY29uZHM6IDUKICAgICAgICByZWFkaW5lc3NQcm9iZToKICAgICAgICAgIGh0dHBHZXQ6CiAgICAgICAgICAgIHBhdGg6IC9oZWFsdGh6CiAgICAgICAgICAgIHBvcnQ6IDgwODAKICAgICAgICAgICAgc2NoZW1lOiBIVFRQCiAgICAgICAgICBpbml0aWFsRGVsYXlTZWNvbmRzOiAxCiAgICAgICAgICB0aW1lb3V0U2Vjb25kczogNQogICAgICAtIG5hbWU6IGhlYWx0aHoKICAgICAgICBpbWFnZTogZ2NyLmlvL2dvb2dsZV9jb250YWluZXJzL2V4ZWNoZWFsdGh6OjEuMAogICAgICAgIHJlc291cmNlczoKICAgICAgICAgIGxpbWl0czoKICAgICAgICAgICAgY3B1OiAxMG0KICAgICAgICAgICAgbWVtb3J5OiAyME1pCiAgICAgICAgYXJnczoKICAgICAgICAtIC1jbWQ9bnNsb29rdXAga3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5rdWJlLmxvY2FsIGxvY2FsaG9zdCA+L2Rldi9udWxsCiAgICAgICAgLSAtcG9ydD04MDgwCiAgICAgICAgcG9ydHM6CiAgICAgICAgLSBjb250YWluZXJQb3J0OiA4MDgwCiAgICAgICAgICBwcm90b2NvbDogVENQCiAgICAgIHZvbHVtZXM6CiAgICAgIC0gbmFtZTogZXRjZC1zdG9yYWdlCiAgICAgICAgZW1wdHlEaXI6IHt9CiAgICAgIGRuc1BvbGljeTogRGVmYXVsdCAgIyBEb24ndCB1c2UgY2x1c3RlciBETlMuCg==
  - path: /etc/kubernetes/addons/skydns-svc.yaml
    owner: root
    permissions: '0640'
    encoding: base64
    content: YXBpVmVyc2lvbjogdjEKa2luZDogU2VydmljZQptZXRhZGF0YToKICBuYW1lOiBrdWJlLWRucwogIG5hbWVzcGFjZToga3ViZS1zeXN0ZW0KICBsYWJlbHM6CiAgICBrOHMtYXBwOiBrdWJlLWRucwogICAga3ViZXJuZXRlcy5pby9jbHVzdGVyLXNlcnZpY2U6ICJ0cnVlIgogICAga3ViZXJuZXRlcy5pby9uYW1lOiAiS3ViZUROUyIKc3BlYzoKICBzZWxlY3RvcjoKICAgIGs4cy1hcHA6IGt1YmUtZG5zCiAgY2x1c3RlcklQOiAxMC4xNi4wLjMKICBwb3J0czoKICAtIG5hbWU6IGRucwogICAgcG9ydDogNTMKICAgIHByb3RvY29sOiBVRFAKICAtIG5hbWU6IGRucy10Y3AKICAgIHBvcnQ6IDUzCiAgICBwcm90b2NvbDogVENQCg==
coreos:
  update:
    group: stable
    reboot-strategy: 'off'
  units:
    - name: systemd-networkd-wait-online.service
      drop-ins:
        - name: 50-check-github-is-reachable.conf
          content: "[Service]\nExecStart=/bin/sh -x -c \\\n  'until curl --silent --fail https://status.github.com/api/status.json | grep -q \\\"good\\\"; do sleep 2; done'\n"
    - name: weave-network.target
      enable: true
      content: |
        [Unit]
        Description=Weave Network Setup Complete
        Documentation=man:systemd.special(7)
        RefuseManualStart=no
        After=network-online.target
        [Install]
        WantedBy=multi-user.target
        WantedBy=kubernetes-master.target
        WantedBy=kubernetes-node.target
    - name: kubernetes-master.target
      enable: true
      command: start
      content: |
        [Unit]
        Description=Kubernetes Cluster Master
        Documentation=http://kubernetes.io/
        RefuseManualStart=no
        After=weave-network.target
        Requires=weave-network.target
        ConditionHost=kube-00
        Wants=kube-apiserver.service
        Wants=kube-scheduler.service
        Wants=kube-controller-manager.service
        Wants=kube-proxy.service
        [Install]
        WantedBy=multi-user.target
    - name: kubernetes-node.target
      enable: true
      command: start
      content: |
        [Unit]
        Description=Kubernetes Cluster Node
        Documentation=http://kubernetes.io/
        RefuseManualStart=no
        After=weave-network.target
        Requires=weave-network.target
        ConditionHost=!kube-00
        Wants=kube-proxy.service
        Wants=kubelet.service
        [Install]
        WantedBy=multi-user.target
    - name: 10-weave.network
      runtime: false
      content: |
        [Match]
        Type=bridge
        Name=weave*
        [Network]
    - name: install-weave.service
      enable: true
      content: "[Unit]\nAfter=network-online.target\nAfter=docker.service\nBefore=weave.service\nDescription=Install Weave\nDocumentation=http://docs.weave.works/\nRequires=network-online.target\n[Service]\nEnvironmentFile=-/etc/weave.%H.env\nEnvironmentFile=-/etc/weave.env\nType=oneshot\nRemainAfterExit=yes\nTimeoutStartSec=0\nExecStartPre=/bin/mkdir -p /opt/bin/\nExecStartPre=/opt/bin/curl-retry.sh \\\n  --silent \\\n  --location \\\n  git.io/weave \\\n  --output /opt/bin/weave\nExecStartPre=/usr/bin/chmod +x /opt/bin/weave\nExecStart=/opt/bin/weave setup\n[Install]\nWantedBy=weave-network.target\nWantedBy=weave.service\n"
    - name: weaveproxy.service
      enable: true
      content: >
        [Unit]

        After=install-weave.service

        After=docker.service

        Description=Weave proxy for Docker API

        Documentation=http://docs.weave.works/

        Requires=docker.service

        Requires=install-weave.service

        [Service]

        EnvironmentFile=-/etc/weave.%H.env

        EnvironmentFile=-/etc/weave.env

        ExecStartPre=/opt/bin/weave launch-proxy --rewrite-inspect --without-dns

        ExecStart=/usr/bin/docker attach weaveproxy

        Restart=on-failure

        ExecStop=/opt/bin/weave stop-proxy

        [Install]

        WantedBy=weave-network.target
    - name: weave.service
      enable: true
      content: |
        [Unit]
        After=install-weave.service
        After=docker.service
        Description=Weave Network Router
        Documentation=http://docs.weave.works/
        Requires=docker.service
        Requires=install-weave.service
        [Service]
        TimeoutStartSec=0
        EnvironmentFile=-/etc/weave.%H.env
        EnvironmentFile=-/etc/weave.env
        ExecStartPre=/opt/bin/weave launch-router $WEAVE_PEERS
        ExecStart=/usr/bin/docker attach weave
        Restart=on-failure
        ExecStop=/opt/bin/weave stop-router
        [Install]
        WantedBy=weave-network.target
    - name: weave-expose.service
      enable: true
      content: |
        [Unit]
        After=install-weave.service
        After=weave.service
        After=docker.service
        Documentation=http://docs.weave.works/
        Requires=docker.service
        Requires=install-weave.service
        Requires=weave.service
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        TimeoutStartSec=0
        EnvironmentFile=-/etc/weave.%H.env
        EnvironmentFile=-/etc/weave.env
        ExecStart=/opt/bin/weave expose
        ExecStop=/opt/bin/weave hide
        [Install]
        WantedBy=weave-network.target
    - name: install-kubernetes.service
      enable: true
      content: >
        [Unit]

        After=network-online.target

        Before=kube-apiserver.service

        Before=kube-controller-manager.service

        Before=kubelet.service

        Before=kube-proxy.service

        Description=Download Kubernetes Binaries

        Documentation=http://kubernetes.io/

        Requires=network-online.target

        [Service]

        Environment=KUBE_RELEASE_TARBALL=https://github.com/kubernetes/kubernetes/releases/download/v1.1.2/kubernetes.tar.gz

        ExecStartPre=/bin/mkdir -p /opt/

        ExecStart=/opt/bin/curl-retry.sh --silent --location
        $KUBE_RELEASE_TARBALL --output /tmp/kubernetes.tgz

        ExecStart=/bin/tar xzvf /tmp/kubernetes.tgz -C /tmp/

        ExecStart=/bin/tar xzvf
        /tmp/kubernetes/server/kubernetes-server-linux-amd64.tar.gz -C /opt

        ExecStartPost=/bin/chmod o+rx -R /opt/kubernetes

        ExecStartPost=/bin/ln -s /opt/kubernetes/server/bin/kubectl /opt/bin/

        ExecStartPost=/bin/mv /tmp/kubernetes/examples/guestbook
        /home/core/guestbook-example

        ExecStartPost=/bin/chown core. -R /home/core/guestbook-example

        ExecStartPost=/bin/rm -rf /tmp/kubernetes

        ExecStartPost=/bin/sed 's/# type: LoadBalancer/type: NodePort/' -i
        /home/core/guestbook-example/frontend-service.yaml

        RemainAfterExit=yes

        Type=oneshot

        [Install]

        WantedBy=kubernetes-master.target

        WantedBy=kubernetes-node.target
    - name: kube-apiserver.service
      enable: true
      content: "[Unit]\nAfter=install-kubernetes.service\nBefore=kube-controller-manager.service\nBefore=kube-scheduler.service\nConditionFileIsExecutable=/opt/kubernetes/server/bin/kube-apiserver\nDescription=Kubernetes API Server\nDocumentation=http://kubernetes.io/\nWants=install-kubernetes.service\nConditionHost=kube-00\n[Service]\nExecStart=/opt/kubernetes/server/bin/kube-apiserver \\\n    --insecure-bind-address=0.0.0.0 \\\n    --advertise-address=$public_ipv4 \\\n    --port=8080 \\\n    $ETCD_SERVERS \\\n    --service-cluster-ip-range=10.16.0.0/12 \\\n    --cloud-provider=vagrant \\\n    --logtostderr=true\nRestart=always\nRestartSec=10\n[Install]\nWantedBy=kubernetes-master.target\n"
    - name: kube-scheduler.service
      enable: true
      content: "[Unit]\nAfter=kube-apiserver.service\nAfter=install-kubernetes.service\nConditionFileIsExecutable=/opt/kubernetes/server/bin/kube-scheduler\nDescription=Kubernetes Scheduler\nDocumentation=http://kubernetes.io/\nWants=kube-apiserver.service\nConditionHost=kube-00\n[Service]\nExecStart=/opt/kubernetes/server/bin/kube-scheduler \\\n    --logtostderr=true \\\n    --master=127.0.0.1:8080\nRestart=always\nRestartSec=10\n[Install]\nWantedBy=kubernetes-master.target\n"
    - name: kube-controller-manager.service
      enable: true
      content: "[Unit]\nAfter=install-kubernetes.service\nAfter=kube-apiserver.service\nConditionFileIsExecutable=/opt/kubernetes/server/bin/kube-controller-manager\nDescription=Kubernetes Controller Manager\nDocumentation=http://kubernetes.io/\nWants=kube-apiserver.service\nWants=install-kubernetes.service\nConditionHost=kube-00\n[Service]\nExecStart=/opt/kubernetes/server/bin/kube-controller-manager \\\n    --master=127.0.0.1:8080 \\\n    --logtostderr=true\nRestart=always\nRestartSec=10\n[Install]\nWantedBy=kubernetes-master.target\n"
    - name: kubelet.service
      enable: true
      content: "[Unit]\nAfter=install-kubernetes.service\nConditionFileIsExecutable=/opt/kubernetes/server/bin/kubelet\nDescription=Kubernetes Kubelet\nDocumentation=http://kubernetes.io/\nWants=install-kubernetes.service\nConditionHost=!kube-00\n[Service]\nExecStartPre=/bin/mkdir -p /etc/kubernetes/manifests/\nExecStart=/opt/kubernetes/server/bin/kubelet \\\n    --docker-endpoint=unix:/var/run/weave/weave.sock \\\n    --address=0.0.0.0 \\\n    --port=10250 \\\n    --hostname-override=%H \\\n    --api-servers=http://kube-00:8080 \\\n    --logtostderr=true \\\n    --cluster-dns=10.16.0.3 \\\n    --cluster-domain=kube.local \\\n    --config=/etc/kubernetes/manifests/\nRestart=always\nRestartSec=10\n[Install]\nWantedBy=kubernetes-node.target\n"
    - name: kube-proxy.service
      enable: true
      content: "[Unit]\nAfter=install-kubernetes.service\nConditionFileIsExecutable=/opt/kubernetes/server/bin/kube-proxy\nDescription=Kubernetes Proxy\nDocumentation=http://kubernetes.io/\nWants=install-kubernetes.service\n[Service]\nExecStart=/opt/kubernetes/server/bin/kube-proxy \\\n     --master=http://kube-00:8080 \\\n     --logtostderr=true\nRestart=always\nRestartSec=10\n[Install]\nWantedBy=kubernetes-master.target\nWantedBy=kubernetes-node.target\n"
    - name: kube-create-addons.service
      enable: true
      content: >
        [Unit]

        After=install-kubernetes.service

        ConditionFileIsExecutable=/opt/kubernetes/server/bin/kubectl

        ConditionPathIsDirectory=/etc/kubernetes/addons/

        ConditionHost=kube-00

        Description=Kubernetes Addons

        Documentation=http://kubernetes.io/

        Wants=install-kubernetes.service

        Wants=kube-apiserver.service

        [Service]

        Type=oneshot

        RemainAfterExit=no

        ExecStart=/bin/bash -c 'until /opt/kubernetes/server/bin/kubectl create
        -f /etc/kubernetes/addons/; do sleep 2; done'

        SuccessExitStatus=1

        [Install]

        WantedBy=kubernetes-master.target
    - name: kube-apiserver.service
      drop-ins:
        - name: 50-etcd-initial-cluster.conf
          content: >
            [Service]

            ${Environment}