#cloud-config
write_files:
  - path: /etc/hosts
    permissions: '0755'
    owner: root
    content: |
      172.16.0.9  zzkubernetes-kube02
      172.16.0.8  zzkubernetes-kube01
      172.16.0.7  zzkubernetes-kube00
      172.16.0.6  zzkubernetes-etcd02
      172.16.0.5  zzkubernetes-etcd01
      172.16.0.4  zzkubernetes-etcd00
 
coreos:
  units:
    - name: etcd2.service
      enable: true
      command: start
    - name: etcd2.service
      drop-ins:
        - name: 50-etcd-initial-cluster.conf
          content: >
            [Service]

            Environment=ETCD_INITIAL_CLUSTER=zzkubernetes-etcd00=http://zzkubernetes-etcd00:2380,zzkubernetes-etcd01=http://zzkubernetes-etcd01:2380,zzkubernetes-etcd02=http://zzkubernetes-etcd02:2380
  etcd2:
    name: '%H'
    initial-cluster-token: etcd-cluster
    initial-advertise-peer-urls: 'http://%H:2380'
    listen-peer-urls: 'http://%H:2380'
    listen-client-urls: 'http://0.0.0.0:2379,http://0.0.0.0:4001'
    advertise-client-urls: 'http://%H:2379,http://%H:4001'
    initial-cluster-state: new
  update:
    group: stable
    reboot-strategy: 'off'
